# Generated by Django 6.0.4 on 2026-04-26 20:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='materiel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('description', models.TextField(max_length=500)),
                ('date_achat', models.DateField()),
                ('etat', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='personnel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='affectation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_affectation', models.DateField()),
                ('date_retour', models.DateField(blank=True, null=True)),
                ('materiel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='materiel.materiel')),
                ('personnel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='materiel.personnel')),
            ],
        ),
        migrations.CreateModel(
            name='reparation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_reparation', models.DateField()),
                ('description', models.TextField(max_length=500)),
                ('cout', models.DecimalField(decimal_places=2, max_digits=10)),
                ('materiel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='materiel.materiel')),
            ],
        ),
    ]
