# Generated by Django 6.0.4 on 2026-04-26 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materiel', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='materiel',
            name='etat',
            field=models.CharField(choices=[('en service', 'En service'), ('en panne', 'En panne'), ('en réparation', 'En réparation')], max_length=100),
        ),
    ]
