# Generated by Django 6.0.4 on 2026-04-28 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materiel', '0002_alter_materiel_etat'),
    ]

    operations = [
        migrations.AddField(
            model_name='materiel',
            name='statut',
            field=models.CharField(choices=[('disponible', 'Disponible'), ('affecté', 'Affecté'), ('en réparation', 'En réparation')], default='disponible', max_length=20),
        ),
    ]
